Fixed Open SSL namespace issues.
- Was getting the following error due to the `Authenticators` module
  not being properly namespaced:

      NameError: uninitialized constant Gemsmith::Authenticators::RubyGems::OpenSSL
- This was due to the loading/requiring of the `Authenticators` modules
  within the context of Rake.